# Generated by Django 3.2.5 on 2021-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='commentaire',
            field=models.TextField(blank=True, default=''),
        ),
    ]
