# Generated by Django 3.2.5 on 2021-10-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_heure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date-heure: JJ.MM.AAAA HH:MM (H+1)'),
        ),
    ]
