# Generated by Django 3.2.5 on 2021-09-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('duree', models.TimeField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6, verbose_name=0)),
            ],
        ),
    ]
