# Generated by Django 3.2.5 on 2021-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_prestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
