# Generated by Django 3.2.5 on 2021-09-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_prestation_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='pour',
            field=models.CharField(choices=[('Courts', 'Courts'), ('Longs', 'Longs')], default='/', max_length=6),
        ),
    ]
