# Generated by Django 3.2.5 on 2021-09-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_prestation_pour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='pour',
            field=models.CharField(choices=[('Courts', 'Courts'), ('Longs', 'Longs'), ('/', '/')], default='', max_length=6),
        ),
    ]
