# Generated by Django 3.2.5 on 2021-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_prestation_pour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='heure',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_heure',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
