# Generated by Django 3.2.5 on 2021-09-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_prestation_pour'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='prestation',
            field=models.ManyToManyField(related_name='prestation', to='reservations.Prestation'),
        ),
    ]
