# Generated by Django 3.2.5 on 2021-09-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_reservation_prestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='prestation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='prestations',
            field=models.ManyToManyField(blank=True, related_name='prestations', to='reservations.Prestation'),
        ),
    ]
