# Generated by Django 3.2.7 on 2021-10-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20210929_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='prestations',
            field=models.ManyToManyField(related_name='prestations', to='reservations.Prestation'),
        ),
    ]
